"""MCP server exposing the GDPR retrievers and agent as tools.

Runs over stdio so it can be wired into MCP clients (e.g. Claude Desktop):

    {
      "mcpServers": {
        "gdpr": {
          "command": "C:/.../gdpr-smart-agent/venv/Scripts/python.exe",
          "args": ["-m", "src.mcp.server"],
          "cwd": "C:/.../gdpr-smart-agent"
        }
      }
    }

Tools
-----
- search_gdpr(query, k)         : semantic search over GDPR paragraphs (vector)
- related_articles(query, limit): articles linked to those named in the query (graph)
- ask_gdpr(question)            : full routed agent answer with citations
                                   (generated with THIS SERVER's OpenAI/Anthropic key)
- ask_gdpr_client(question)     : same routing + retrieval as ask_gdpr, but the
                                   answer is generated by the CALLING CLIENT's own
                                   LLM via MCP sampling, not this server's key —
                                   see the docstring below for why that matters.
"""

from __future__ import annotations

from dotenv import load_dotenv
from mcp.server.fastmcp import Context, FastMCP
from mcp.types import SamplingMessage, TextContent
from neo4j.exceptions import GqlError

from src.agent.graph import answer_question
from src.agent.nodes import (
    GRAPH_SYSTEM_PROMPT,
    SYSTEM_PROMPT,
    _format_context,
    classify_route,
    graph_retrieve_node,
    retrieve_node,
)
from src.rag import graph_retriever
from src.rag.vector_retriever import RetrievedChunk, retrieve

load_dotenv()

mcp = FastMCP("gdpr-smart-agent")


def _serialize(chunk: RetrievedChunk) -> dict:
    return {
        "citation": chunk.citation,
        "article_number": chunk.article_number,
        "paragraph_number": chunk.paragraph_number,
        "title": chunk.title,
        "url": chunk.url,
        "text": chunk.text,
    }


@mcp.tool()
def search_gdpr(query: str, k: int = 4) -> list[dict]:
    """Semantic search over GDPR article paragraphs.

    Use for definitional or substantive questions ("what is personal data?").
    Returns the k most relevant passages with article/paragraph citations.
    """
    return [_serialize(c) for c in retrieve(query, k=k)]


@mcp.tool()
def related_articles(query: str, limit: int = 6) -> list[dict]:
    """Find GDPR articles related to those named in the query.

    Use for relationship questions ("what articles reference Article 6?").
    Traverses cross-references and chapter siblings in the knowledge graph.
    Requires the Neo4j graph to be running and loaded.
    """
    try:
        return [_serialize(c) for c in graph_retriever.retrieve(query, limit=limit)]
    except GqlError as exc:
        # This tool is graph-only by design, so a connectivity failure is
        # reported clearly rather than silently falling back to vector search
        # (unlike ask_gdpr, whose routed agent already degrades gracefully).
        raise RuntimeError(
            "Neo4j graph is unreachable. Start it with `docker compose up -d "
            "neo4j` and load it with `python -m src.graph.load_graph`."
        ) from exc


@mcp.tool()
def ask_gdpr(question: str) -> dict:
    """Answer a GDPR question with citations using the full routed agent.

    The agent automatically picks vector or graph retrieval based on the
    question, then generates a grounded, cited answer.
    """
    result = answer_question(question)
    return {
        "answer": result["answer"],
        "route": result.get("route"),
        "sources": [_serialize(c) for c in result.get("chunks", [])],
    }


@mcp.tool()
async def ask_gdpr_client(question: str, ctx: Context) -> dict:
    """Answer a GDPR question with citations, like ask_gdpr — but generate the
    answer with the CALLING CLIENT's own LLM instead of this server's.

    Routing and retrieval (vector or graph, same logic as ask_gdpr) still run
    server-side. Only generation is delegated, via MCP sampling
    (``session.create_message``): this server sends the retrieved context and
    a system prompt to the client, and the client's own model writes the
    answer. Two reasons to prefer this over ask_gdpr:

    1. No duplicate LLM spend — ask_gdpr pays for a completion with this
       server's OpenAI/Anthropic key even though the calling assistant
       already has its own model. This tool pays nothing (server-side) for
       generation.
    2. The answer comes back in the calling assistant's own model/voice
       rather than a fixed server-side model.

    Requires an MCP client with sampling support (e.g. Claude Desktop). Raises
    an MCP error if the connected client doesn't support sampling.
    """
    route = classify_route(question)
    state = {"question": question}
    state = graph_retrieve_node(state) if route == "graph" else retrieve_node(state)
    chunks = state.get("chunks", [])

    if not chunks:
        return {
            "answer": "I couldn't find any relevant GDPR provisions for that question.",
            "route": route,
            "sources": [],
        }

    is_graph = route == "graph"
    system_prompt = GRAPH_SYSTEM_PROMPT if is_graph else SYSTEM_PROMPT
    intro = "Related articles:" if is_graph else "Context:"
    context = _format_context(chunks)

    result = await ctx.session.create_message(
        messages=[
            SamplingMessage(
                role="user",
                content=TextContent(
                    type="text",
                    text=f"{intro}\n{context}\n\nQuestion: {question}",
                ),
            )
        ],
        system_prompt=system_prompt,
        max_tokens=800,
    )

    answer = result.content.text if isinstance(result.content, TextContent) else str(result.content)

    return {
        "answer": answer,
        "route": route,
        "sources": [_serialize(c) for c in chunks],
        "generated_by": result.model or "client",
    }


def main() -> None:
    mcp.run()  # stdio transport


if __name__ == "__main__":
    main()
